# 🐍 Python for Data Science
## Phase 1: Python Fundamentals
---
**Goal:** Build strong programming basics from the ground up.

**Topics Covered:**
1. Variables & Data Types
2. Operators
3. Data Structures: Lists, Tuples, Sets, Dictionaries
4. Conditional Statements
5. Loops
6. Exception Handling


---
## 📌 Section 1: Variables & Data Types
> Variables store data. Python is **dynamically typed** — no need to declare types.


In [ ]:
# ── Basic Variable Assignment ──────────────────────────────────────────────
name       = "MJ"        # str
age        = 30             # int
height     = 5.6            # float
is_student = False           # bool
score      = None           # NoneType

print(f"Name: {name}, Age: {age}, Height: {height}")
print(f"Student: {is_student}, Score: {score}")


In [ ]:
# ── type() and isinstance() ───────────────────────────────────────────────
print(type(name))           # <class 'str'>
print(type(age))            # <class 'int'>
print(type(height))         # <class 'float'>
print(type(is_student))     # <class 'bool'>
print(type(score))          # <class 'NoneType'>

print(isinstance(age, int))       # True
print(isinstance(name, (str, int))) # True — check multiple types


In [ ]:
# ── Type Conversion (Casting) ─────────────────────────────────────────────
x = int("42")         # str → int
y = float("3.14")     # str → float
z = str(100)          # int → str
b = bool(1)           # 0 → False (0, "", None, [], {} are all falsy)

print(x, type(x))     # 42 <class 'int'>
print(y, type(y))     # 3.14 <class 'float'>
print(z, type(z))     # 100 <class 'str'>
print(b)              # False

# Strings
greeting = "Hello, World!"
print(greeting.upper())
print(greeting.lower())
print(greeting.replace("World", "Python"))
print(greeting.split(", "))     # ['Hello', 'World!']
print(len(greeting))            # 13
print(greeting[0:8])            # Hello


In [2]:
# ── f-Strings (formatted string literals) — Python 3.6+ ──────────────────
name = "Bob"
age  = 30
pi   = 3.14159

print(f"My name is {name} and I am {age} years old.")
print(f"Pi rounded to 2 decimal places: {pi:.2f}")
print(f"Age in 10 years: {age + 10}")
print(f"Is adult: {age >= 18}")


My name is Bob and I am 30 years old.
Pi rounded to 2 decimal places: 3.14
Age in 10 years: 40
Is adult: True


---
## 📌 Section 2: Operators


In [3]:
# ── Arithmetic Operators ──────────────────────────────────────────────────
a, b = 17, 5
print(f"Addition:       {a} + {b} = {a + b}")
print(f"Subtraction:    {a} - {b} = {a - b}")
print(f"Multiplication: {a} * {b} = {a * b}")
print(f"Division:       {a} / {b} = {a / b}")
print(f"Floor Division: {a} // {b} = {a // b}")
print(f"Modulus:        {a} % {b} = {a % b}")
print(f"Exponentiation: {a} ** {b} = {a ** b}")


Addition:       17 + 5 = 22
Subtraction:    17 - 5 = 12
Multiplication: 17 * 5 = 85
Division:       17 / 5 = 3.4
Floor Division: 17 // 5 = 3
Modulus:        17 % 5 = 2
Exponentiation: 17 ** 5 = 1419857


In [4]:
# ── Comparison & Logical Operators ────────────────────────────────────────
x, y = 10, 20
print(x == y)   # False
print(x != y)   # True
print(x < y)    # True
print(x >= y)   # False

# Logical
print(x > 5 and y > 15)    # True
print(x > 15 or y > 15)    # True
print(not (x == y))        # True

# Assignment operators
n = 10
n += 5;  print(n)   # 15
n *= 2;  print(n)   # 30
n //= 4; print(n)   # 7


False
True
True
False
True
True
True
15
30
7


---
## 📌 Section 3: Data Structures
### 3a. Lists — Ordered, Mutable


In [5]:
# ── Creating Lists ────────────────────────────────────────────────────────
fruits   = ["apple", "banana", "cherry"]
numbers  = [10, 20, 30, 40, 50] # 1: 10 ----- n-1 (3)
mixed    = [1, "hello", 3.14, True, None]
nested   = [[1, 2], [3, 4], [5, 6]]

print(fruits)
print(numbers[0], numbers[-1])    # First and last
print(numbers[1:4])               # Slicing: [20, 30, 40]
print(nested[2][1])               # 3 — nested access


['apple', 'banana', 'cherry']
10 50
[20, 30, 40]
6


In [6]:
# ── List Methods ──────────────────────────────────────────────────────────
fruits = ["apple","apple", "banana", "cherry"]

fruits.append("mango")          # Add to end
fruits.insert(1, "blueberry")   # Insert at index
fruits.remove("banana")         # Remove first occurrence
popped = fruits.pop()           # Remove & return last item
fruits.sort()                   # Sort in-place

print(fruits)
print(f"Popped: {popped}")
print(f"Length: {len(fruits)}")
print(f"Count of 'apple': {fruits.count('apple')}")


['apple', 'apple', 'blueberry', 'cherry']
Popped: mango
Length: 4
Count of 'apple': 2


In [7]:
# ── List Comprehension ────────────────────────────────────────────────────
# Syntax: [expression for item in iterable if condition]

squares  = [x**2 for x in range(1, 11)]
evens    = [x for x in range(1, 21) if x % 2 == 0]
words    = ["hello", "world", "python"]
upper    = [w.upper() for w in words]
flat     = [n for row in [[1,2],[3,4],[5,6]] for n in row]

print(squares)
print(evens)
print(upper)
print(flat)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
['HELLO', 'WORLD', 'PYTHON']
[1, 2, 3, 4, 5, 6]


### 3b. Tuples — Ordered, Immutable


In [8]:
# ── Tuples ────────────────────────────────────────────────────────────────
point    = (3, 7, 4)
# colors   = ("red", "green", "blue")
# single   = (42)   # comma required for single-element tuple

# print(point[0], point[-1])
# print(colors[1:3])
# print(single)

# Unpacking
x, y, z = point
print(f"x={x}, y={y}, z={z}")

a, *rest, z = (1, 2, 3, 4, 5, 6)
print(f"a={a}, rest={rest}, z={z}")

# Tuples as dict keys (lists can't!)
coords = {(0,0): "origin", (1,0): "right", (0,1): "up"}
print(coords[(0,0)])

# Functions returning multiple values → tuple
def min_max(lst):
    return min(lst), max(lst)

lo, hi = min_max([3, 9, 4, 7,10,2])
print(f"Min={lo}, Max={hi}")


x=3, y=7, z=4
a=1, rest=[2, 3, 4, 5], z=6
origin
Min=2, Max=10


### 3c. Sets — Unordered, No Duplicates


In [9]:
# ── Sets ──────────────────────────────────────────────────────────────────
# nums    = {1, 2, 3, 2, 1, 3}   # duplicates removed
# fruits  = {"banana", "cherry"}

# print(nums)     # {1, 2, 3} — order may vary

# fruits.add("mango")
# fruits.discard("banana")    # safe — no error if missing

# print(f"apple in fruits: {'apple' in fruits}")

# Set operations
a = {1, 2, 3, 4, 5}
b = {4, 5, 6, 7, 8}

print(f"Union:        {a | b}")
print(f"Intersection: {a & b}")
print(f"Difference:   {a - b}")
print(f"Sym Diff:     {a ^ b}")
print(f"Subset check: {a.issubset({1,2,3,4,5,6,7})}")

# Remove duplicates from a list
my_list = [1, 5, 2, 5, 3, 1, 4]
unique = sorted(list(set(my_list)))
print(f"Unique sorted: {unique}")


Union:        {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference:   {1, 2, 3}
Sym Diff:     {1, 2, 3, 6, 7, 8}
Subset check: True
Unique sorted: [1, 2, 3, 4, 5]


### 3d. Dictionaries — Key-Value Pairs


In [10]:
# ── Dictionaries ──────────────────────────────────────────────────────────
student = {
    "name":   "Alice",
    "age":    22,
    "grades": [90, 85, 92],
    "active": True
}

# Access
print(student["name"])
print(student.get("gpa", 0.0))   # returns default if key missing

# Modify
student["age"] = 23
student["email"] = "alice@uni.edu"
del student["active"]


# Iterate
for key, value in student.items():
    print(f"  {key}: {value}")

print(list(student.keys()))
print(list(student.values()))


Alice
0.0
  name: Alice
  age: 23
  grades: [90, 85, 92]
  email: alice@uni.edu
['name', 'age', 'grades', 'email']
['Alice', 23, [90, 85, 92], 'alice@uni.edu']


---
## 📌 Section 4: Conditional Statements


In [11]:
# ── if / elif / else ──────────────────────────────────────────────────────
scores = [95, 78, 62, 45, 83]

for score in scores:
    if score >= 90:
        grade = "A"
    elif score >= 80:
        grade = "B"
    elif score >= 70:
        grade = "C"
    elif score >= 60:
        grade = "D"
    else:
        grade = "F"
    print(f"Score: {score:3d}  →  Grade: {grade}")


Score:  95  →  Grade: A
Score:  78  →  Grade: C
Score:  62  →  Grade: D
Score:  45  →  Grade: F
Score:  83  →  Grade: B


In [12]:
# ── Ternary Operator (conditional expression) ─────────────────────────────
age = 20
status = "Adult" if age >= 18 else "Minor"
print(status)

# Chained ternary
x = 0
label = "positive" if x > 0 else "negative" if x < 0 else "zero"
print(label)

# # Membership testing in conditions
allowed_users = {"alice", "bob", "carol"}
user = "MJ"
if user in allowed_users:
    print(f"Access granted for {user}")
else:
    print("Access denied")

# # match-case (Python 3.10+, like switch)
day = "Sunday"
match day:
    case "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday":
        print("Weekday")
    case "Saturday" | "Sunday":
        print("Weekend")
    case _:
        print("Invalid day")


Adult
zero
Access denied
Weekend


---
## 📌 Section 5: Loops


In [13]:
# ── for Loop ──────────────────────────────────────────────────────────────
# Iterate a list
fruits = ["apple", "banana", "cherry", "mango", "Strawberyy"]
for fruit in fruits:
    print(fruit)

print("---")

# range()
for i in range(0, 10, 2):      # start, stop, step
    print(i, end=" ")           # 0 2 4 6 8
print()

# # enumerate() — index + value
for i, fruit in enumerate(fruits, start=1):
    print(f"{i}. {fruit}")


apple
banana
cherry
mango
Strawberyy
---
0 2 4 6 8 
1. apple
2. banana
3. cherry
4. mango
5. Strawberyy


In [14]:
# ── while Loop ────────────────────────────────────────────────────────────
count = 1
while count <= 5:
    print(f"Count: {count}")
    count += 1

# break and continue
# print("\nbreak example:")
# for n in range(1, 11):
#     if n == 6:
#         break
#     print(n, end=" ")

# print("\ncontinue example (skip odd):")
for n in range(1, 11):
    if n % 2 != 0:
        continue
    print(n, end=" ")

# # while-else
print("\n\nwhile-else:")
n = 1
while n <= 5:
    print(n, end=" ")
    n += 1
else:
    print("\n→ Loop finished normally (else block ran)")


Count: 1
Count: 2
Count: 3
Count: 4
Count: 5
2 4 6 8 10 

while-else:
1 2 3 4 5 
→ Loop finished normally (else block ran)


---
## 📌 Section 6: Functions


In [15]:
# ── Basic Functions ───────────────────────────────────────────────────────
def greet(name):
    """Return a greeting string."""  # docstring
    return f"Hello, {name}!"

print(greet("MJ"))
print(greet.__doc__)   # access docstring

# Default argument
def power(base, exp=2):
    return base ** exp

print(power(3))      # 9  (exp defaults to 2)
print(power(2, 10))  # 1024

# Multiple return values
def stats(numbers):
    return min(numbers), max(numbers), sum(numbers)/len(numbers)

lo, hi, avg = stats([4, 7, 2, 9, 1, 5])
print(f"Min={lo}, Max={hi}, Avg={avg:.2f}")


Hello, MJ!
Return a greeting string.
9
1024
Min=1, Max=9, Avg=4.67


---
## 📌 Section 7: Exception Handling


In [16]:
# ── try / except / else / finally ────────────────────────────────────────
def safe_divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        print("⚠️  Cannot divide by zero")
        return None
    except TypeError as e:
        print(f"⚠️  Type error: {e}")
        return None
    else:
        print(f"✅  Result: {result}")
        return result
    finally:
        print("   [finally block always runs]")

safe_divide(10, 2)
print()
safe_divide(10, 0)
print()
safe_divide(10, "x")
print()


✅  Result: 5.0
   [finally block always runs]

⚠️  Cannot divide by zero
   [finally block always runs]

⚠️  Type error: unsupported operand type(s) for /: 'int' and 'str'
   [finally block always runs]



In [17]:
# ── Common Built-in Exceptions ────────────────────────────────────────────
examples = [
    (lambda: int("abc"),          "ValueError"),
    (lambda: [1,2,3][10],         "IndexError"),
    (lambda: {"a":1}["z"],        "KeyError"),
    (lambda: "a" + 1,             "TypeError"),
    (lambda: open("nonexist.txt"),"FileNotFoundError"),
]

for fn, name in examples:
    try:
        fn()
    except Exception as e:
        print(f"{name:25s} → {e}")


ValueError                → invalid literal for int() with base 10: 'abc'
IndexError                → list index out of range
KeyError                  → 'z'
TypeError                 → can only concatenate str (not "int") to str
FileNotFoundError         → [Errno 2] No such file or directory: 'nonexist.txt'


---
## 📌 Section 8: File Handling


In [18]:
import os

# ── Write and Read Text Files ──────────────────────────────────────────────
# Write
with open("sample.txt", "w") as f:
    f.write("Python for Data Science\n")
    f.write("Phase 1: Fundamentals\n")
    f.write("Phase 2: Data Handling\n")
print("✅ File written")

# Read entire content
with open("sample.txt", "r") as f:
    content = f.read()
print("--- Full content ---")
print(content)

# Read line by line
print("--- Line by line ---")
with open("sample.txt", "r") as f:
    for i, line in enumerate(f, 1):
        print(f"{i}: {line.rstrip()}")

# Read into list
with open("sample.txt", "r") as f:
    lines = f.readlines()
print(f"Total lines: {len(lines)}")

os.remove("sample.txt")  # cleanup


✅ File written
--- Full content ---
Python for Data Science
Phase 1: Fundamentals
Phase 2: Data Handling

--- Line by line ---
1: Python for Data Science
2: Phase 1: Fundamentals
3: Phase 2: Data Handling
Total lines: 3


In [19]:
import json

# ── JSON File Handling ─────────────────────────────────────────────────────
students = [
    {"name": "Alice", "score": 95, "courses": ["Math", "CS"]},
    {"name": "Bob",   "score": 82, "courses": ["CS", "Stats"]},
    {"name": "Carol", "score": 91, "courses": ["Math", "Stats"]},
]

# # Write JSON
with open("students.json", "w") as f:
    json.dump(students, f, indent=2)
print("✅ JSON written")

# Read JSON
with open("students.json", "r") as f:
    loaded = json.load(f)

for s in loaded:
    print(f"{s['name']:8s}  Score: {s['score']}  Courses: {', '.join(s['courses'])}")

# json.dumps / loads — work with strings
json_str = json.dumps({"key": "value", "nums": [1,2,3]})
print(f"\nJSON string: {json_str}")
data     = json.loads(json_str)
print(f"Parsed:      {data}")

os.remove("students.json")


✅ JSON written
Alice     Score: 95  Courses: Math, CS
Bob       Score: 82  Courses: CS, Stats
Carol     Score: 91  Courses: Math, Stats

JSON string: {"key": "value", "nums": [1, 2, 3]}
Parsed:      {'key': 'value', 'nums': [1, 2, 3]}


---
## ✅ Phase 1 Complete!

**➡️ Next up: Phase 2 — Python for Data Handling**

Proceed to `Phase2_Python_Data_Handling.ipynb`


In [20]:
print("MJ")

MJ


In [21]:

import numpy as np
print(np.random.seed(42))

None


In [22]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [23]:
np.random.seed(30)
print(np.random.randint(1,10,5))

[6 6 5 8 3]


In [24]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.ndim)


(2, 3)
2


In [25]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])


print(arr.shape)
print(arr.ndim)


(2, 2, 3)
3


In [26]:
# (layers, rows, column)

In [27]:
result = []
for x in [1, 2, 3]:
    result.append(x * 2)

In [28]:
print(result)

[2, 4, 6]


In [35]:
arr = np.array([1,2,3])
result = arr-2
print(result)

[-1  0  1]


In [29]:
arr= np.array([1,2,3]) #[5,5,5]
arr+5

array([6, 7, 8])

In [30]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([10,20,30])

arr1*arr2

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [31]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.dot(a, b))


[[19 22]
 [43 50]]


In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
print(a.T)

[[1 3]
 [2 4]]
